_base_: ../base.yaml

experiment:
  name: vpas_clip_vitb16
  output_dir: ./outputs/vpas_clip_vitb16

model:
  name: vpas
  num_layers: 3
  layer_wise_neck: true
  use_discrepancy_filter: true
  prototype_mode: layerwise
  mask_fusion_mode: add
